name: CD

on: 
  workflow_run:
    workflows: ["test"]


jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v2

      - name: Greeting
        run: echo "Start Deployment!"
