name: CD

on: 
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2

      - name: Greeting
        run: echo "Start Deployment!"
