name: CI

on:
  push:
    branches:
      - '**'
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Greeting TestCI
        run: echo "Hello, world! TestCI"

      - name: java version
        run: java -version


      - name: Node Version
        run: node -v


   - name: NPM Version
        run: npm version


