name: CI

on:
  push:
    branches:
      - '**'
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Greeting TestCI
        run: echo "Hello, world! TestCI"

      - name: STEP 1  - Slepp 10
        run: |
        echo "Start STEP 1"
        sleep(10)
        echo "End Step 1"

      - name: S TEP 2  - Slepp 15
        run: |
        echo "Start STEP 2"
        sleep(15)
        echo "End Step 12"

 


