name: CI ALL mamad (all)

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  call-workflow-passing-data:
    strategy:
      matrix:
        region: ["er-central-1", "ap-sotheast-1"]
    uses: ./.github/workflows/reusable_build.yml
    with:
      region: ${{ matrix.region }}





