name: CI

on:
  push:
    branches:
      - '**'
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Greeting TestCI
        run: echo "Hello, world! TestCI"

      - name: Hello world action step
        uses: majidypd/testgh@v2



