name: CI ALL mamad (all)

on:
  push:

jobs:
  call-workflow-passing-data:
    if: github.repository == 'octo-org/octo-repo-prod'
    strategy:
      matrix:
        region: ["er-central-1", "ap-sotheast-1"]
    uses: ./.github/workflows/reusable_build.yml
    with:
      region: ${{ matrix.region }}
      roll: true

