name: CI

on: 
  push:
      tags:        
        - v2
        - v1.*


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Greeting
        run: echo "Hello, world!"

      - name: test 
        run: go test ./...
