name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  call-workflow-passing-data:
    uses: "./build.yml"
    with:
      config-path: "TESTCONFIGPATH"





