name: CI

on:
  push:
    branches:
      - '**'
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.19

    steps:
      - uses: actions/checkout@v2

      - name: Greeting TestCI
        run: echo "Hello, world! TestCI"

      - name: test 
        run: go version
