name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Greeting TestCI
        run: echo "Hello, world! TestCI"

      - name: HASH
        env:
          COMMIT_HASH: "salam"
        run:  echo $COMMIT_HASH

 


