name: CI

on:
  pull_request:
    branches:
      - 'master'
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Greeting TestCI
        run: echo "Hello, world! TestCI"

      - name: STEP 1  - Slepp 10
        run: go run main.go


 


