name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container: ubuntu

    steps:
      - uses: actions/checkout@v3

      - name: Greeting TestCI
        run: echo "Hello, world! TestCI"

      - name: STEP 1  - Slepp 10
        run: ls -la


      - name: Listen
        run: lsof -i -P -n " grep LISTEN"


 


