name: CI

on:
  push:
    branches:
      - '**'
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Greeting TestCI
        run: echo "Hello, world! TestCI"

      - name: Install OpenJDK8
        run: |
            apt-get update && \
            apt-get install -y openjdk-8-jdk && \
            apt-get install -y ant && \
            apt-get clean;


