name: deploy region-2

on: 
  workflow_run:
    workflows: ["CI ALL mamad (all)"]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    strategy:
      matrix:
        region: ["eu-central-1", "ap-sotheast-1"]
    steps:
      - uses: actions/checkout@v2

      - name: Deploy ${{ matrix.region }}
        run: echo ${{ github.event.workflow_run.status }}

