name: deploy STG
on: 
  workflow_dispatch:
    inputs:
      region:
        description: 'Region for deployment'
        type: choice
        options:
          - 'eu-central-1'
          - 'us-east-1'
          - 'me-south-1'
          - 'ap-southeast-1'
          - 'ap-south-1'
        required: true
        default: 'eu-central-1'


env: 
  CHAT_TAG: ${{  github.sha }}

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    environment: prod26

    steps:
      - uses: actions/checkout@v3

      - name: Deploy "TESTTT  TAG"
        run:  ./deploy.sh

  # deploy-k8s:
  #   runs-on: ubuntu-latest
  #   environment: prod2
  #   strategy:
  #     matrix:
  #       region: ["eu-central-1", "ap-sotheast-1"]
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Deploy ${{ matrix.region }}
  #       run: echo ${{ github.event.workflow_run.status }}

