name: deploy STG
on: 
  workflow_run:
    workflows: ["CI ALL mamad (all)"]
    types: 
      - completed

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    environment: prod2
    strategy:
      matrix:
        region: ["eu-central-1", "ap-sotheast-1"]
    steps:
      - uses: actions/checkout@v3

      - name: Deploy ${{ matrix.region }}
        run: echo ${{ github.event.workflow_run.status }}

  deploy-k8s:
    runs-on: ubuntu-latest
    environment: prod2
    strategy:
      matrix:
        region: ["eu-central-1", "ap-sotheast-1"]
    steps:
      - uses: actions/checkout@v3

      - name: Deploy ${{ matrix.region }}
        run: echo ${{ github.event.workflow_run.status }}

