name: deploy region-2

on: 
  workflow_run:
    workflows: ["CI ALL mamad (all)"]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3

      - name: Deploy "ap-sotheast-1"
        run: echo ${{ github.event.workflow_run.status }}

      - name: Deploy eu-central-1
        run: echo ${{ github.event.workflow_run.status }}
