name: deploy STG
on: 
  workflow_dispatch:

env: 
  CHAT_TAG: ${{  github.sha }}

jobs:
  deploy-aws:
    runs-on: ubuntu-latest
    environment: prod26

    steps:
      - uses: actions/checkout@v3

      - name: Deploy "TESTTT  TAG"
        run:  ./deploy.sh

  # deploy-k8s:
  #   runs-on: ubuntu-latest
  #   environment: prod2
  #   strategy:
  #     matrix:
  #       region: ["eu-central-1", "ap-sotheast-1"]
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Deploy ${{ matrix.region }}
  #       run: echo ${{ github.event.workflow_run.status }}

