name: deploy region-2

on: 
  workflow_run:
    workflows: ["CI"]
    tags:
      - v*.*.*
    types: 
      - requested

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2

      - name: Deploy region 2
        run: echo "Start Deployment!"
