name: deploy region-1

on: 
  workflow_run:
    workflows: ["CI ALL"]
    types: 
      - completed


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2

      - name: Deploy region 1
        run: echo "Start Deployment!"
