name: Reusable workflow example

on:
  workflow_call:
    inputs:
      region:
        required: false
        type: string      
      roll:
        required: true
        type: boolean

env: 
  CHAT_TAG: "aaa${{  github.ref_name }}"
  TEST_VARIABLE_T: ${{ env.TEST_VARIABLE_T}}

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy "TESTTT  TAG"
        run:  ./deploy.sh
