name: Reusable workflow example

on:
  workflow_call:
    inputs:
      region:
        required: false
        type: string      
      roll:
        required: true
        type: boolean

jobs:
  triage:
    runs-on: ubuntu-latest
    if: inputs.roll
    steps:
      - uses: actions/checkout@v3
      - name: Run ${{ inputs.region }}
      - name: Deploy "TESTTT  TAG"
        run:  ./deploy.sh
